name: Deploy AWS Lambda Docker image to ECR

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Build and Update lambda image
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ steps.login-ecr.outputs.registry }}/lambda-numpy:amd64"
          platforms: linux/amd64
